Hide non-partner charts in 'helm3-library' catalog
rancher/helm3-charts pull request #71
Opened 2021-11-11 10:43 UTC by doflamingo721

Linked issues:
https://github.com/rancher/rancher/issues/35351

2021-11-15 19:09 UTC, PennyScissors requested changes
The chart `dynatrace-oneagent-operator` is actually a partner chart, but they forgot to add the partner label. Can you add this at the top of their questions.yaml files and remove the min/max? Everything else looks good.
```
labels:
  io.rancher.certified: partner
```

2021-11-16 06:51 UTC, doflamingo721 commented
> The chart `dynatrace-oneagent-operator` is actually a partner chart, but they forgot to add the partner label. Can you add this at the top of their questions.yaml files and remove the min/max? Everything else looks good.
> 
> ```
> labels:
>   io.rancher.certified: partner
> ```
@PennyScissors I made the required changes. Can you please review it again?

2021-11-18 00:26 UTC, PennyScissors requested changes
After reviewing https://github.com/rancher/helm3-charts/pull/72, looks like dynatrace-oneagent-operator shouldn't be part of this PR since it is not a partner chart. Since you already made the necessary changes in the other PR for hiding partner charts, you should revert the changes done to dynatrace in this PR.

2021-11-19 17:38 UTC, PennyScissors requested changes

2021-11-19 17:38 UTC, pennyscissors commented on charts/dynatrace-oneagent-operator/v0.7.0/questions.yml
> -  io.rancher.certified: partner
This needs to be reverted, the dynatrace-oneagent-operator chart shouldn't be modified in this PR. Since it is a partner chart, [this](https://github.com/rancher/helm3-charts/pull/72) PR for hiding partner charts already handled adding the missing partner label, and hiding the chart.

2021-11-22 13:08 UTC, doflamingo721 commented on charts/dynatrace-oneagent-operator/v0.7.0/questions.yml
> -  io.rancher.certified: partner
@PennyScissors I have reverted the changes made to the dynatrace-oneagent-operator. Could you please review it once again. Thanks

2021-11-22 17:59 UTC, deniseschannon approved these changes

2021-11-22 18:00 UTC, merged